hackgdsc2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "main"

urlpatterns = [
    path('predict/prediction', views.prediction),
    path('predict/', views.predict, name="predict"),
    path('', views.home, name="home"),
]

main/models.py
import email
from email import message
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=40)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

main/views.py
from re import sub
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
from .models import Contact

# ML
import pandas as pd
from sklearn.preprocessing import LabelEncoder  
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split  

# Create your views here.
def home(request):
    if(request.method == 'POST'):
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        Contact.objects.create(name=name, email=email, subject=subject, message=message)
        return render(request, 'index.html', {"contact":"success"})

    return render(request, 'index.html')

def predict(request):
    return render(request, 'predict.html')

def prediction(request):
        if(request.method == 'POST'):
            
            ten = int(request.POST['metriculate'])
            twelve = int(request.POST['intermediate'])
            enterance = int(request.POST['enterance'])
            intrest = request.POST['intrest']

            inp = [ten, twelve, enterance, intrest]

            fs = FileSystemStorage()
            data = fs.open('final_dataset.csv')

            dataset=pd.read_csv(data)
            X = dataset.iloc[:, :-1].values
            y = dataset.iloc[:, -1].values

            label_encoder_x= LabelEncoder()  
            X[:, 3]= label_encoder_x.fit_transform(X[:, 3])  

            inp[3:4]= label_encoder_x.transform(inp[3:4])
            inp=[inp]

            X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.1, random_state=0)  

            reg = LogisticRegression(random_state = 0)
            reg.fit(X_train, y_train)

            output=reg.predict(inp)[0]
            
            return render(request, 'result.html', {"output": output})

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta content="width=device-width, initial-scale=1.0" name="viewport" />
		<title>Future Scope</title>
		<meta content="We at FUTURE SCOPE helps young budding mind that are ready to explore the world to get the best they can achieve in their life ." name="description" />
		<meta content="" name="keywords" />

		<meta name="twitter:card" content="summary_large_image">
		<meta name='twitter:site' content='@kambojshalabh35'>
		<meta name='twitter:creator' content='@kambojshalabh35'>
		<meta name='twitter:title' content="Future Scope">
		<meta name='twitter:description' content="We at FUTURE SCOPE helps young budding mind that are ready to explore the world to get the best they can achieve in their life .">
		<meta name='twitter:image' content="{% static 'img/og.png' %}">
		<meta name='twitter:domain' content="https://futurescope.pythonanywhere.com/">

		<meta property='og:title' content="Future Scope" />
		<meta property='og:site_name' content='Future Scope' />
		<meta property='og:url' content="https://futurescope.pythonanywhere.com/" />
		<meta property='og:description' content="We at FUTURE SCOPE helps young budding mind that are ready to explore the world to get the best they can achieve in their life ." />
		<meta property='og:type' content='website' />

		<meta property='og:image' content="{% static 'img/og.png' %}" />
		<meta property='og:image:type' content='image/png'>
		<meta property='og:image:alt' content='...' />
		<meta property='og:locale' content='India' />

		<meta name='pinterest:title' content='Future Scope' />
		<meta name='pinterest:domain' content="https://futurescope.pythonanywhere.com/" />
		<meta name='pinterest:description' content='We at FUTURE SCOPE helps young budding mind that are ready to explore the world to get the best they can achieve in their life .' />
		<meta name='pinterest:image' content="{% static 'img/og.png' %}" />

		<link href="{% static 'img/favicon.png' %}" rel="icon" />
		<link
			href="{% static 'img/apple-touch-icon.png' %}"
			rel="apple-touch-icon"
		/>
		<link
			href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
			rel="stylesheet"
		/>
		<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
		/>
		<link
			href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css"
			rel="stylesheet"
		/>
		<link
			rel="stylesheet"
			href="https://unpkg.com/swiper/swiper-bundle.min.css"
		/>
		<link
			href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
			rel="stylesheet"
		/>
		<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
		<link href="{% static 'css/style.css' %}" rel="stylesheet" />
	</head>
	<body>
		<header id="header" class="fixed-top">
			<div class="container d-flex align-items-center justify-content-between">
				<h1 class="logo"><a href="{% url 'main:home' %}">Future Scope</a></h1>
				<nav id="navbar" class="navbar">
					<ul>
						<li>
							<a class="nav-link scrollto" href="{% url 'main:home' %}#hero"
								>Home</a
							>
						</li>
						<li>
							<a class="nav-link scrollto" href="{% url 'main:home' %}#about"
								>About</a
							>
						</li>
						<li>
							<a
								class="nav-link scrollto"
								href="{% url 'main:predict' %}#predict"
								>Predict</a
							>
						</li>
						<li>
							<a class="nav-link scrollto" href="{% url 'main:home' %}#team"
								>Team</a
							>
						</li>
						<li>
							<a class="nav-link scrollto" href="{% url 'main:home' %}#contact"
								>Contact</a
							>
						</li>
					</ul>
					<i class="bi bi-list mobile-nav-toggle"></i>
				</nav>
			</div>
		</header>
		<main id="main">{% block body %}{% endblock body %}</main>
		<footer id="footer">
			<div class="container py-4">
				<div class="text-center">
					<div class="copyright">
						&copy; Copyright <strong><span>Future Scope</span></strong
						>. All Rights Reserved
					</div>
					<div class="credits">
						Designed by
						<a href="https://www.youtube.com/channel/UC5IBRfk_HH6kJEHV07ODxFg"
							>Team Pentium Coders</a
						>
					</div>
				</div>
			</div>
		</footer>
		<div id="preloader"></div>
		<a
			href="#"
			class="back-to-top d-flex align-items-center justify-content-center"
			><i class="bi bi-arrow-up-short"></i
		></a>
		<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
			crossorigin="anonymous"
		></script>
		<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
		<script src="{% static 'js/main.js' %}"></script>
	</body>
</html>

templates/index.html
{% extends 'base.html' %}{% block body %}
<section id="hero" class="d-flex align-items-center">
	<div
		class="container position-relative"
		data-aos="fade-up"
		data-aos-delay="100"
	>
		<div class="row justify-content-center">
			<div class="col-xl-7 col-lg-9 text-center">
				<h1>Future Scope</h1>
				<h2>Advisors With Assistance</h2>
			</div>
		</div>
		<div class="text-center">
			<a href="#about" class="btn-get-started scrollto">Get Started</a>
		</div>
		<div class="row icon-boxes">
			<div
				class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0"
				data-aos="zoom-in"
				data-aos-delay="200"
			>
				<div class="icon-box">
					<div class="icon"><i class="ri-stack-line"></i></div>
					<h4 class="title"><a href="">Education encompasses</a></h4>
					<p class="description">
						Education encompasses elements we often think of in the context of
						learning and development. These elements generally have a defined
						beginning and end, and can be tracked.
					</p>
				</div>
			</div>
			<div
				class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0"
				data-aos="zoom-in"
				data-aos-delay="300"
			>
				<div class="icon-box">
					<div class="icon"><i class="ri-palette-line"></i></div>
					<h4 class="title"><a href="">Experience</a></h4>
					<p class="description">
						Experience includes elements that generally occur while employees
						are in the workplace, and which may include stretch assignments, job
						rotations, and special projects.
					</p>
				</div>
			</div>
			<div
				class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0"
				data-aos="zoom-in"
				data-aos-delay="400"
			>
				<div class="icon-box">
					<div class="icon"><i class="ri-command-line"></i></div>
					<h4 class="title"><a href="">Exposure</a></h4>
					<p class="description">
						Exposure comprises learning elements that involve interaction and
						relationships. It helps employees to develop by building connections
						with other professionals and thought leaders.
					</p>
				</div>
			</div>
			<div
				class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0"
				data-aos="zoom-in"
				data-aos-delay="500"
			>
				<div class="icon-box">
					<div class="icon"><i class="ri-fingerprint-line"></i></div>
					<h4 class="title"><a href="">Environment</a></h4>
					<p class="description">
						Environment covers the various tools, systems, and other
						infrastructure that employees use on the job to learn or support
						them in their work.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>
<section id="about" class="about">
	<div class="container" data-aos="fade-up">
		<div class="section-title">
			<h2>About Us</h2>
			<p>
				Are you looking for some Career coach ?
			</p>
		</div>
		<div class="row content">
			<div class="col-lg-6">
				<p>
					We at FUTURE SCOPE helps young budding mind that are ready to explore the world to get the best they can achieve in their life.
				</p>
				<ul>
					<li>
						<i class="ri-check-double-line"></i> We make sure that you are advised in the best direction
					</li>
					<li>
						<i class="ri-check-double-line"></i> Not on the bases of your marks but also vocational subjects
					</li>
					<li>
						<i class="ri-check-double-line"></i> That some of you might took up or hobbies that can be converted into profession
					</li>
				</ul>
			</div>
			<div class="col-lg-6 pt-4 pt-lg-0">
				<p>
					Our main is to help innovative mind to stop wasting time and consulting various career coaches and just start taking steps on the success road
				</p>
				<a href="#" class="btn-learn-more">Learn More</a>
			</div>
		</div>
	</div>
</section>
<section id="cta" class="cta">
	<div class="container" data-aos="zoom-in">
		<div class="text-center">
			<h3>Predict your Career</h3>
			<p>
				Are you looking for some Career coach ?
If choosing the correct career is your dream, making it simple is ours. Share your dream aspirations and we will make it happen for you.
			</p>
			<a class="cta-btn" href="{% url 'main:predict' %}">Predict</a>
		</div>
	</div>
</section>
<section id="team" class="team section-bg">
	<div class="container" data-aos="fade-up">
		<div class="section-title">
			<h2>Team</h2>
			<p>
				The people who dedicated their time at FUTURESCOPE share the vision and values of our community. We're driven by the idea that the best work is born from diligence, craftsmanship and fun.
			</p>
		</div>
		<div class="row">
			<div
				class="col-lg-3 col-md-6 d-flex align-items-stretch mx-auto"
				data-aos="fade-up"
				data-aos-delay="100"
			>
				<div class="member">
					<div class="member-img">
						<img src="static/img/team/team-1.png" class="img-fluid" alt="" />
						<div class="social">
							<a href=""><i class="bi bi-twitter"></i></a>
							<a href=""><i class="bi bi-facebook"></i></a>
							<a href=""><i class="bi bi-instagram"></i></a>
							<a href=""><i class="bi bi-linkedin"></i></a>
						</div>
					</div>
					<div class="member-info">
						<h4>Shalabh Kamboj</h4>
						<span>Web Developer</span>
					</div>
				</div>
			</div>
			<div
				class="col-lg-3 col-md-6 d-flex align-items-stretch mx-auto"
				data-aos="fade-up"
				data-aos-delay="200"
			>
				<div class="member">
					<div class="member-img">
						<img src="static/img/team/team-2.png" class="img-fluid" alt="" />
						<div class="social">
							<a href=""><i class="bi bi-twitter"></i></a>
							<a href=""><i class="bi bi-facebook"></i></a>
							<a href=""><i class="bi bi-instagram"></i></a>
							<a href=""><i class="bi bi-linkedin"></i></a>
						</div>
					</div>
					<div class="member-info">
						<h4>Tanisha Srivastava</h4>
						<span>Data Scientist</span>
					</div>
				</div>
			</div>
			<div
				class="col-lg-3 col-md-6 d-flex align-items-stretch mx-auto"
				data-aos="fade-up"
				data-aos-delay="300"
			>
				<div class="member">
					<div class="member-img">
						<img src="static/img/team/team-3.png" class="img-fluid" alt="" />
						<div class="social">
							<a href=""><i class="bi bi-twitter"></i></a>
							<a href=""><i class="bi bi-facebook"></i></a>
							<a href=""><i class="bi bi-instagram"></i></a>
							<a href=""><i class="bi bi-linkedin"></i></a>
						</div>
					</div>
					<div class="member-info">
						<h4>Utkarsh Kumar</h4>
						<span>Web Developer</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section id="contact" class="contact">
	<div class="container" data-aos="fade-up">
		<div class="section-title">
			<h2>Contact</h2>
			<p>
				We're here to help you level up. We're just one click away to help you take your Problems and find innovative idea to solve them  Fill in the form to share more details about your problem. Or your favorite gum flavor. Either way, we'd love to talk.
			</p>
		</div>
		<div class="row mt-5">
			<div class="col-lg-4">
				<div class="info">
					<div class="address">
						<i class="bi bi-geo-alt"></i>
						<h4>Location:</h4>
						<p>India</p>
					</div>
					<div class="email">
						<i class="bi bi-envelope"></i>
						<h4>Email:</h4>
						<p>contact@test.com</p>
					</div>
					<div class="phone">
						<i class="bi bi-phone"></i>
						<h4>Call:</h4>
						<p>+91 00000 00000</p>
					</div>
				</div>
			</div>
			<div class="col-lg-8 mt-5 mt-lg-0">
				<form action="" method="post" role="form" class="php-email-form">
					{% csrf_token %}
					<div class="row">
						<div class="col-md-6 form-group">
							<input
								type="text"
								name="name"
								class="form-control"
								id="name"
								placeholder="Your Name"
								required
							/>
						</div>
						<div class="col-md-6 form-group mt-3 mt-md-0">
							<input
								type="email"
								class="form-control"
								name="email"
								id="email"
								placeholder="Your Email"
								required
							/>
						</div>
					</div>
					<div class="form-group mt-3">
						<input
							type="text"
							class="form-control"
							name="subject"
							id="subject"
							placeholder="Subject"
							required
						/>
					</div>
					<div class="form-group mt-3">
						<textarea
							class="form-control"
							name="message"
							rows="5"
							placeholder="Message"
							required
						></textarea>
					</div>
					<div class="my-3">
						{% if contact %}
						<div class="sent-message">
							Your message has been sent. Thank you!
						</div>
						{% endif %}
					</div>
					<div class="text-center">
						<button type="submit">Send Message</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
{% endblock body %}

templates/predict.html
{% extends 'base.html' %}{% block body %}
<section id="breadcrumbs" class="breadcrumbs">
	<div class="container">
		<div class="d-flex justify-content-between align-items-center">
			<h2>Predict your Career</h2>
			<ol>
				<li><a href="{% url 'main:home' %}">Home</a></li>
				<li>Predict</li>
			</ol>
		</div>
	</div>
</section>
<section id="predict" class="predict">
	<div class="container">
		<div class="section-title">
			<h2>Predict</h2>
			<p>
				Your career advise is just a click away! make sure to be transparent so
				that we can provide you with the best success tip!
			</p>
		</div>
		<form action="prediction" method="post">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-6 col-11 mx-auto">
					<input
						type="text"
						class="form-control"
						name="metriculate"
						placeholder="Matriculation Marks (%age)"
					/>
				</div>
				<div class="col-md-6 col-11 mx-auto mt-3 mt-md-0">
					<input
						type="text"
						class="form-control"
						name="intermediate"
						placeholder="Intermediate Marks (%age)"
					/>
				</div>
				<div class="col-md-6 col-11 mx-auto mt-3">
					<input
						type="text"
						class="form-control"
						name="enterance"
						placeholder="Enterance Marks (%age)"
					/>
				</div>
				<div class="col-md-6 col-11 mx-auto mt-3">
					<select name="intrest" id="intrest" class="form-select">
						<option value="">-- Interested In --</option>
						<option value="coding">Coding</option>
						<option value="current affairs">Current Affairs</option>
						<option value="healthcare">Health Care</option>
						<option value="law">Law</option>
						<option value="modelling">Modelling</option>
					</select>
				</div>
				<div class="mt-3">
					<input type="submit" class="btn btn-outline-light" value="Predict" />
				</div>
			</div>
		</form>
	</div>
</section>
{% endblock body %}

templates/result.html
{% extends 'base.html' %}{% block body %}
<section id="breadcrumbs" class="breadcrumbs">
	<div class="container">
		<div class="d-flex justify-content-between align-items-center">
			<h2>Prediction Result</h2>
			<ol>
				<li><a href="{% url 'main:home' %}">Home</a></li>
				<li>Result</li>
			</ol>
		</div>
	</div>
</section>
<section id="predict" class="predict">
	<div class="container">
		<div class="section-title">
			<h2>Predict</h2>
			<p>According to our analysis you should do {{output}}.</p>
		</div>
		<div class="container text-center">
			{% if output == "Engineering" %}<lottie-player
				src="https://assets3.lottiefiles.com/packages/lf20_f8arnpdn.json"
				background="transparent"
				speed="1"
				class="col-4 mx-auto"
				loop
				autoplay
			></lottie-player
			>{% elif output == "Doctor" %}<lottie-player
				src="https://assets3.lottiefiles.com/packages/lf20_l13zwx3i.json"
				background="transparent"
				speed="1"
				class="col-6 mx-auto"
				loop
				autoplay
			></lottie-player
			>{% elif output == "Fashion Designer" %}<lottie-player
				src="https://assets4.lottiefiles.com/packages/lf20_gn0tojcq.json"
				background="transparent"
				speed="1"
				class="col-6 mx-auto"
				loop
				autoplay
			></lottie-player
			>{% elif output == "Lawyer" %}<lottie-player
				src="https://assets6.lottiefiles.com/packages/lf20_rdkrsaca.json"
				background="transparent"
				speed="1"
				class="col-6 mx-auto"
				loop
				autoplay
			></lottie-player
			>{% elif output == "UPSC" %}<lottie-player
				src="https://assets8.lottiefiles.com/packages/lf20_vq5wzcvx.json"
				background="transparent"
				speed="1"
				class="col-4 mx-auto"
				loop
				autoplay
			></lottie-player
			>{% endif %}
		</div>
	</div>
</section>
{% endblock body %}